name: Build and deploy develop docs

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: write

jobs:
  deploy:
    name: Build and deploy develop documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install java
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: 'oracle'
          java-version: '25'
      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          enable-cache: false
      - name: Build develop docs
        run: |
          uv run -- build_docs.py develop
          cd docs/build
          echo "This branch is automatically maintained by GitHub Actions." > README.md
          cat > index.html << EOL
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting</title>
            <noscript>
              <meta http-equiv="refresh" content="1; url=latest/" />
            </noscript>
            <script>
              window.location.replace(
                "latest/" + window.location.search + window.location.hash
              );
            </script>
          </head>
          <body>
            Redirecting to <a href="latest/">latest/</a>...
          </body>
          </html>
          EOL
      - name: Deploy develop docs
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          keep_files: true
