name: Tests

on: [push, pull_request]

env:
  PY_COLORS: 1
  COLUMNS: 100

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.x"]
        architecture: [x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Upgrade pip, setuptools and wheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel
      - name: Install requirements
        run: python -m pip install --upgrade pytest lxml
      - name: Run tests
        run: python -m pytest
